# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/auth/auth.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "auth.ActivateRequest" do
    optional :subject, :string, 2
    optional :github_token, :string, 1
  end
  add_message "auth.ActivateResponse" do
    optional :pach_token, :string, 1
  end
  add_message "auth.DeactivateRequest" do
  end
  add_message "auth.DeactivateResponse" do
  end
  add_message "auth.GetAdminsRequest" do
  end
  add_message "auth.GetAdminsResponse" do
    repeated :admins, :string, 1
  end
  add_message "auth.ModifyAdminsRequest" do
    repeated :add, :string, 1
    repeated :remove, :string, 2
  end
  add_message "auth.ModifyAdminsResponse" do
  end
  add_message "auth.TokenInfo" do
    optional :subject, :string, 1
    optional :source, :enum, 2, "auth.TokenInfo.TokenSource"
  end
  add_enum "auth.TokenInfo.TokenSource" do
    value :INVALID, 0
    value :AUTHENTICATE, 1
    value :GET_TOKEN, 2
  end
  add_message "auth.AuthenticateRequest" do
    optional :github_token, :string, 1
  end
  add_message "auth.AuthenticateResponse" do
    optional :pach_token, :string, 1
  end
  add_message "auth.WhoAmIRequest" do
  end
  add_message "auth.WhoAmIResponse" do
    optional :username, :string, 1
    optional :is_admin, :bool, 2
  end
  add_message "auth.ACL" do
    map :entries, :string, :enum, 1, "auth.Scope"
  end
  add_message "auth.Users" do
    map :usernames, :string, :bool, 1
  end
  add_message "auth.Groups" do
    map :groups, :string, :bool, 1
  end
  add_message "auth.AuthorizeRequest" do
    optional :repo, :string, 1
    optional :scope, :enum, 2, "auth.Scope"
  end
  add_message "auth.AuthorizeResponse" do
    optional :authorized, :bool, 1
  end
  add_message "auth.GetScopeRequest" do
    optional :username, :string, 1
    repeated :repos, :string, 2
  end
  add_message "auth.GetScopeResponse" do
    repeated :scopes, :enum, 1, "auth.Scope"
  end
  add_message "auth.SetScopeRequest" do
    optional :username, :string, 1
    optional :repo, :string, 2
    optional :scope, :enum, 3, "auth.Scope"
  end
  add_message "auth.SetScopeResponse" do
  end
  add_message "auth.GetACLRequest" do
    optional :repo, :string, 1
  end
  add_message "auth.ACLEntry" do
    optional :username, :string, 1
    optional :scope, :enum, 2, "auth.Scope"
  end
  add_message "auth.GetACLResponse" do
    repeated :entries, :message, 1, "auth.ACLEntry"
    repeated :robot_entries, :message, 2, "auth.ACLEntry"
  end
  add_message "auth.SetACLRequest" do
    optional :repo, :string, 1
    repeated :entries, :message, 2, "auth.ACLEntry"
  end
  add_message "auth.SetACLResponse" do
  end
  add_message "auth.GetAuthTokenRequest" do
    optional :subject, :string, 1
    optional :ttl, :int64, 2
  end
  add_message "auth.GetAuthTokenResponse" do
    optional :subject, :string, 2
    optional :token, :string, 1
  end
  add_message "auth.ExtendAuthTokenRequest" do
    optional :token, :string, 1
    optional :ttl, :int64, 2
  end
  add_message "auth.ExtendAuthTokenResponse" do
  end
  add_message "auth.RevokeAuthTokenRequest" do
    optional :token, :string, 1
  end
  add_message "auth.RevokeAuthTokenResponse" do
  end
  add_message "auth.SetGroupsForUserRequest" do
    optional :username, :string, 1
    repeated :groups, :string, 2
  end
  add_message "auth.SetGroupsForUserResponse" do
  end
  add_message "auth.ModifyMembersRequest" do
    optional :group, :string, 1
    repeated :add, :string, 2
    repeated :remove, :string, 3
  end
  add_message "auth.ModifyMembersResponse" do
  end
  add_message "auth.GetGroupsRequest" do
    optional :username, :string, 1
  end
  add_message "auth.GetGroupsResponse" do
    repeated :groups, :string, 1
  end
  add_message "auth.GetUsersRequest" do
    optional :group, :string, 1
  end
  add_message "auth.GetUsersResponse" do
    repeated :usernames, :string, 1
  end
  add_enum "auth.Scope" do
    value :NONE, 0
    value :READER, 1
    value :WRITER, 2
    value :OWNER, 3
  end
end

module Auth
  ActivateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.ActivateRequest").msgclass
  ActivateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.ActivateResponse").msgclass
  DeactivateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.DeactivateRequest").msgclass
  DeactivateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.DeactivateResponse").msgclass
  GetAdminsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.GetAdminsRequest").msgclass
  GetAdminsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.GetAdminsResponse").msgclass
  ModifyAdminsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.ModifyAdminsRequest").msgclass
  ModifyAdminsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.ModifyAdminsResponse").msgclass
  TokenInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.TokenInfo").msgclass
  TokenInfo::TokenSource = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.TokenInfo.TokenSource").enummodule
  AuthenticateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.AuthenticateRequest").msgclass
  AuthenticateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.AuthenticateResponse").msgclass
  WhoAmIRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.WhoAmIRequest").msgclass
  WhoAmIResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.WhoAmIResponse").msgclass
  ACL = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.ACL").msgclass
  Users = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.Users").msgclass
  Groups = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.Groups").msgclass
  AuthorizeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.AuthorizeRequest").msgclass
  AuthorizeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.AuthorizeResponse").msgclass
  GetScopeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.GetScopeRequest").msgclass
  GetScopeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.GetScopeResponse").msgclass
  SetScopeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.SetScopeRequest").msgclass
  SetScopeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.SetScopeResponse").msgclass
  GetACLRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.GetACLRequest").msgclass
  ACLEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.ACLEntry").msgclass
  GetACLResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.GetACLResponse").msgclass
  SetACLRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.SetACLRequest").msgclass
  SetACLResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.SetACLResponse").msgclass
  GetAuthTokenRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.GetAuthTokenRequest").msgclass
  GetAuthTokenResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.GetAuthTokenResponse").msgclass
  ExtendAuthTokenRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.ExtendAuthTokenRequest").msgclass
  ExtendAuthTokenResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.ExtendAuthTokenResponse").msgclass
  RevokeAuthTokenRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.RevokeAuthTokenRequest").msgclass
  RevokeAuthTokenResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.RevokeAuthTokenResponse").msgclass
  SetGroupsForUserRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.SetGroupsForUserRequest").msgclass
  SetGroupsForUserResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.SetGroupsForUserResponse").msgclass
  ModifyMembersRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.ModifyMembersRequest").msgclass
  ModifyMembersResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.ModifyMembersResponse").msgclass
  GetGroupsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.GetGroupsRequest").msgclass
  GetGroupsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.GetGroupsResponse").msgclass
  GetUsersRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.GetUsersRequest").msgclass
  GetUsersResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.GetUsersResponse").msgclass
  Scope = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.Scope").enummodule
end
