# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: client/health/health.proto for package 'health'

require 'grpc'
require 'client/health/health_pb'

module Pachyderm
module Health
  module Health
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'health.Health'

      rpc :Health, Google::Protobuf::Empty, Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
end
