# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/pfs/pfs.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/timestamp_pb'
require 'google/protobuf/wrappers_pb'
require 'client/auth/auth_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "pfs.Repo" do
    optional :name, :string, 1
  end
  add_message "pfs.Branch" do
    optional :repo, :message, 1, "pfs.Repo"
    optional :name, :string, 2
  end
  add_message "pfs.BranchInfo" do
    optional :branch, :message, 4, "pfs.Branch"
    optional :head, :message, 2, "pfs.Commit"
    repeated :provenance, :message, 3, "pfs.Branch"
    repeated :subvenance, :message, 5, "pfs.Branch"
    repeated :direct_provenance, :message, 6, "pfs.Branch"
    optional :name, :string, 1
  end
  add_message "pfs.BranchInfos" do
    repeated :branch_info, :message, 1, "pfs.BranchInfo"
  end
  add_message "pfs.File" do
    optional :commit, :message, 1, "pfs.Commit"
    optional :path, :string, 2
  end
  add_message "pfs.Block" do
    optional :hash, :string, 1
  end
  add_message "pfs.Object" do
    optional :hash, :string, 1
  end
  add_message "pfs.Tag" do
    optional :name, :string, 1
  end
  add_message "pfs.RepoInfo" do
    optional :repo, :message, 1, "pfs.Repo"
    optional :created, :message, 2, "google.protobuf.Timestamp"
    optional :size_bytes, :uint64, 3
    optional :description, :string, 5
    repeated :branches, :message, 7, "pfs.Branch"
    optional :auth_info, :message, 6, "pfs.RepoAuthInfo"
  end
  add_message "pfs.RepoAuthInfo" do
    optional :access_level, :enum, 1, "auth.Scope"
  end
  add_message "pfs.Commit" do
    optional :repo, :message, 1, "pfs.Repo"
    optional :id, :string, 2
  end
  add_message "pfs.CommitRange" do
    optional :lower, :message, 1, "pfs.Commit"
    optional :upper, :message, 2, "pfs.Commit"
  end
  add_message "pfs.CommitInfo" do
    optional :commit, :message, 1, "pfs.Commit"
    optional :description, :string, 8
    optional :parent_commit, :message, 2, "pfs.Commit"
    repeated :child_commits, :message, 11, "pfs.Commit"
    optional :started, :message, 3, "google.protobuf.Timestamp"
    optional :finished, :message, 4, "google.protobuf.Timestamp"
    optional :size_bytes, :uint64, 5
    repeated :provenance, :message, 6, "pfs.Commit"
    repeated :branch_provenance, :message, 10, "pfs.Branch"
    optional :ready_provenance, :int64, 12
    repeated :subvenance, :message, 9, "pfs.CommitRange"
    optional :tree, :message, 7, "pfs.Object"
  end
  add_message "pfs.FileInfo" do
    optional :file, :message, 1, "pfs.File"
    optional :file_type, :enum, 2, "pfs.FileType"
    optional :size_bytes, :uint64, 3
    repeated :children, :string, 6
    repeated :objects, :message, 8, "pfs.Object"
    optional :hash, :bytes, 7
  end
  add_message "pfs.ByteRange" do
    optional :lower, :uint64, 1
    optional :upper, :uint64, 2
  end
  add_message "pfs.BlockRef" do
    optional :block, :message, 1, "pfs.Block"
    optional :range, :message, 2, "pfs.ByteRange"
  end
  add_message "pfs.ObjectInfo" do
    optional :object, :message, 1, "pfs.Object"
    optional :block_ref, :message, 2, "pfs.BlockRef"
  end
  add_message "pfs.CreateRepoRequest" do
    optional :repo, :message, 1, "pfs.Repo"
    optional :description, :string, 3
    optional :update, :bool, 4
  end
  add_message "pfs.InspectRepoRequest" do
    optional :repo, :message, 1, "pfs.Repo"
  end
  add_message "pfs.ListRepoRequest" do
  end
  add_message "pfs.ListRepoResponse" do
    repeated :repo_info, :message, 1, "pfs.RepoInfo"
  end
  add_message "pfs.DeleteRepoRequest" do
    optional :repo, :message, 1, "pfs.Repo"
    optional :force, :bool, 2
    optional :all, :bool, 3
  end
  add_message "pfs.StartCommitRequest" do
    optional :parent, :message, 1, "pfs.Commit"
    optional :description, :string, 4
    optional :branch, :string, 3
    repeated :provenance, :message, 2, "pfs.Commit"
  end
  add_message "pfs.BuildCommitRequest" do
    optional :parent, :message, 1, "pfs.Commit"
    optional :branch, :string, 4
    repeated :provenance, :message, 2, "pfs.Commit"
    optional :tree, :message, 3, "pfs.Object"
    optional :ID, :string, 5
  end
  add_message "pfs.FinishCommitRequest" do
    optional :commit, :message, 1, "pfs.Commit"
    optional :description, :string, 2
    optional :tree, :message, 3, "pfs.Object"
    optional :empty, :bool, 4
  end
  add_message "pfs.InspectCommitRequest" do
    optional :commit, :message, 1, "pfs.Commit"
    optional :block_state, :enum, 2, "pfs.CommitState"
  end
  add_message "pfs.ListCommitRequest" do
    optional :repo, :message, 1, "pfs.Repo"
    optional :from, :message, 2, "pfs.Commit"
    optional :to, :message, 3, "pfs.Commit"
    optional :number, :uint64, 4
  end
  add_message "pfs.CommitInfos" do
    repeated :commit_info, :message, 1, "pfs.CommitInfo"
  end
  add_message "pfs.CreateBranchRequest" do
    optional :head, :message, 1, "pfs.Commit"
    optional :s_branch, :string, 2
    optional :branch, :message, 3, "pfs.Branch"
    repeated :provenance, :message, 4, "pfs.Branch"
  end
  add_message "pfs.InspectBranchRequest" do
    optional :branch, :message, 1, "pfs.Branch"
  end
  add_message "pfs.ListBranchRequest" do
    optional :repo, :message, 1, "pfs.Repo"
  end
  add_message "pfs.DeleteBranchRequest" do
    optional :branch, :message, 1, "pfs.Branch"
    optional :force, :bool, 2
  end
  add_message "pfs.DeleteCommitRequest" do
    optional :commit, :message, 1, "pfs.Commit"
  end
  add_message "pfs.FlushCommitRequest" do
    repeated :commits, :message, 1, "pfs.Commit"
    repeated :to_repos, :message, 2, "pfs.Repo"
  end
  add_message "pfs.SubscribeCommitRequest" do
    optional :repo, :message, 1, "pfs.Repo"
    optional :branch, :string, 2
    optional :from, :message, 3, "pfs.Commit"
    optional :state, :enum, 4, "pfs.CommitState"
  end
  add_message "pfs.GetFileRequest" do
    optional :file, :message, 1, "pfs.File"
    optional :offset_bytes, :int64, 2
    optional :size_bytes, :int64, 3
  end
  add_message "pfs.OverwriteIndex" do
    optional :index, :int64, 1
  end
  add_message "pfs.PutFileRequest" do
    optional :file, :message, 1, "pfs.File"
    optional :value, :bytes, 3
    optional :url, :string, 5
    optional :recursive, :bool, 6
    optional :delimiter, :enum, 7, "pfs.Delimiter"
    optional :target_file_datums, :int64, 8
    optional :target_file_bytes, :int64, 9
    optional :overwrite_index, :message, 10, "pfs.OverwriteIndex"
  end
  add_message "pfs.PutFileRecord" do
    optional :size_bytes, :int64, 1
    optional :object_hash, :string, 2
    optional :overwrite_index, :message, 3, "pfs.OverwriteIndex"
  end
  add_message "pfs.PutFileRecords" do
    optional :split, :bool, 1
    repeated :records, :message, 2, "pfs.PutFileRecord"
    optional :tombstone, :bool, 3
  end
  add_message "pfs.CopyFileRequest" do
    optional :src, :message, 1, "pfs.File"
    optional :dst, :message, 2, "pfs.File"
    optional :overwrite, :bool, 3
  end
  add_message "pfs.InspectFileRequest" do
    optional :file, :message, 1, "pfs.File"
  end
  add_message "pfs.ListFileRequest" do
    optional :file, :message, 1, "pfs.File"
    optional :full, :bool, 2
  end
  add_message "pfs.GlobFileRequest" do
    optional :commit, :message, 1, "pfs.Commit"
    optional :pattern, :string, 2
  end
  add_message "pfs.FileInfos" do
    repeated :file_info, :message, 1, "pfs.FileInfo"
  end
  add_message "pfs.DiffFileRequest" do
    optional :new_file, :message, 1, "pfs.File"
    optional :old_file, :message, 2, "pfs.File"
    optional :shallow, :bool, 3
  end
  add_message "pfs.DiffFileResponse" do
    repeated :new_files, :message, 1, "pfs.FileInfo"
    repeated :old_files, :message, 2, "pfs.FileInfo"
  end
  add_message "pfs.DeleteFileRequest" do
    optional :file, :message, 1, "pfs.File"
  end
  add_message "pfs.PutObjectRequest" do
    optional :value, :bytes, 1
    repeated :tags, :message, 2, "pfs.Tag"
  end
  add_message "pfs.GetObjectsRequest" do
    repeated :objects, :message, 1, "pfs.Object"
    optional :offset_bytes, :uint64, 2
    optional :size_bytes, :uint64, 3
    optional :total_size, :uint64, 4
  end
  add_message "pfs.TagObjectRequest" do
    optional :object, :message, 1, "pfs.Object"
    repeated :tags, :message, 2, "pfs.Tag"
  end
  add_message "pfs.ListObjectsRequest" do
  end
  add_message "pfs.ListTagsRequest" do
    optional :prefix, :string, 1
    optional :include_object, :bool, 2
  end
  add_message "pfs.ListTagsResponse" do
    optional :tag, :message, 1, "pfs.Tag"
    optional :object, :message, 2, "pfs.Object"
  end
  add_message "pfs.DeleteObjectsRequest" do
    repeated :objects, :message, 1, "pfs.Object"
  end
  add_message "pfs.DeleteObjectsResponse" do
  end
  add_message "pfs.DeleteTagsRequest" do
    repeated :tags, :message, 1, "pfs.Tag"
  end
  add_message "pfs.DeleteTagsResponse" do
  end
  add_message "pfs.CheckObjectRequest" do
    optional :object, :message, 1, "pfs.Object"
  end
  add_message "pfs.CheckObjectResponse" do
    optional :exists, :bool, 1
  end
  add_message "pfs.Objects" do
    repeated :objects, :message, 1, "pfs.Object"
  end
  add_message "pfs.ObjectIndex" do
    map :objects, :string, :message, 1, "pfs.BlockRef"
    map :tags, :string, :message, 2, "pfs.Object"
  end
  add_enum "pfs.FileType" do
    value :RESERVED, 0
    value :FILE, 1
    value :DIR, 2
  end
  add_enum "pfs.CommitState" do
    value :STARTED, 0
    value :READY, 1
    value :FINISHED, 2
  end
  add_enum "pfs.Delimiter" do
    value :NONE, 0
    value :JSON, 1
    value :LINE, 2
  end
end

module Pfs
  Repo = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.Repo").msgclass
  Branch = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.Branch").msgclass
  BranchInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.BranchInfo").msgclass
  BranchInfos = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.BranchInfos").msgclass
  File = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.File").msgclass
  Block = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.Block").msgclass
  Object = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.Object").msgclass
  Tag = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.Tag").msgclass
  RepoInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.RepoInfo").msgclass
  RepoAuthInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.RepoAuthInfo").msgclass
  Commit = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.Commit").msgclass
  CommitRange = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.CommitRange").msgclass
  CommitInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.CommitInfo").msgclass
  FileInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.FileInfo").msgclass
  ByteRange = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.ByteRange").msgclass
  BlockRef = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.BlockRef").msgclass
  ObjectInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.ObjectInfo").msgclass
  CreateRepoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.CreateRepoRequest").msgclass
  InspectRepoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.InspectRepoRequest").msgclass
  ListRepoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.ListRepoRequest").msgclass
  ListRepoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.ListRepoResponse").msgclass
  DeleteRepoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.DeleteRepoRequest").msgclass
  StartCommitRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.StartCommitRequest").msgclass
  BuildCommitRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.BuildCommitRequest").msgclass
  FinishCommitRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.FinishCommitRequest").msgclass
  InspectCommitRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.InspectCommitRequest").msgclass
  ListCommitRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.ListCommitRequest").msgclass
  CommitInfos = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.CommitInfos").msgclass
  CreateBranchRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.CreateBranchRequest").msgclass
  InspectBranchRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.InspectBranchRequest").msgclass
  ListBranchRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.ListBranchRequest").msgclass
  DeleteBranchRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.DeleteBranchRequest").msgclass
  DeleteCommitRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.DeleteCommitRequest").msgclass
  FlushCommitRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.FlushCommitRequest").msgclass
  SubscribeCommitRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.SubscribeCommitRequest").msgclass
  GetFileRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.GetFileRequest").msgclass
  OverwriteIndex = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.OverwriteIndex").msgclass
  PutFileRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.PutFileRequest").msgclass
  PutFileRecord = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.PutFileRecord").msgclass
  PutFileRecords = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.PutFileRecords").msgclass
  CopyFileRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.CopyFileRequest").msgclass
  InspectFileRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.InspectFileRequest").msgclass
  ListFileRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.ListFileRequest").msgclass
  GlobFileRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.GlobFileRequest").msgclass
  FileInfos = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.FileInfos").msgclass
  DiffFileRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.DiffFileRequest").msgclass
  DiffFileResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.DiffFileResponse").msgclass
  DeleteFileRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.DeleteFileRequest").msgclass
  PutObjectRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.PutObjectRequest").msgclass
  GetObjectsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.GetObjectsRequest").msgclass
  TagObjectRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.TagObjectRequest").msgclass
  ListObjectsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.ListObjectsRequest").msgclass
  ListTagsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.ListTagsRequest").msgclass
  ListTagsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.ListTagsResponse").msgclass
  DeleteObjectsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.DeleteObjectsRequest").msgclass
  DeleteObjectsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.DeleteObjectsResponse").msgclass
  DeleteTagsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.DeleteTagsRequest").msgclass
  DeleteTagsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.DeleteTagsResponse").msgclass
  CheckObjectRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.CheckObjectRequest").msgclass
  CheckObjectResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.CheckObjectResponse").msgclass
  Objects = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.Objects").msgclass
  ObjectIndex = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.ObjectIndex").msgclass
  FileType = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.FileType").enummodule
  CommitState = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.CommitState").enummodule
  Delimiter = Google::Protobuf::DescriptorPool.generated_pool.lookup("pfs.Delimiter").enummodule
end
