# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/admin/admin.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'client/pfs/pfs_pb'
require 'client/pps/pps_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "admin.Op1_7" do
    optional :object, :message, 2, "pfs.PutObjectRequest"
    optional :tag, :message, 3, "pfs.TagObjectRequest"
    optional :repo, :message, 4, "pfs.CreateRepoRequest"
    optional :commit, :message, 5, "pfs.BuildCommitRequest"
    optional :branch, :message, 6, "pfs.CreateBranchRequest"
    optional :pipeline, :message, 7, "pps.CreatePipelineRequest"
  end
  add_message "admin.Op" do
    optional :op1_7, :message, 1, "admin.Op1_7"
  end
  add_message "admin.ExtractRequest" do
    optional :URL, :string, 1
    optional :no_objects, :bool, 2
    optional :no_repos, :bool, 3
    optional :no_pipelines, :bool, 4
  end
  add_message "admin.ExtractPipelineRequest" do
    optional :pipeline, :message, 1, "pps.Pipeline"
  end
  add_message "admin.RestoreRequest" do
    optional :op, :message, 1, "admin.Op"
    optional :URL, :string, 2
  end
  add_message "admin.ClusterInfo" do
    optional :id, :string, 1
  end
end

module Admin
  Op1_7 = Google::Protobuf::DescriptorPool.generated_pool.lookup("admin.Op1_7").msgclass
  Op = Google::Protobuf::DescriptorPool.generated_pool.lookup("admin.Op").msgclass
  ExtractRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("admin.ExtractRequest").msgclass
  ExtractPipelineRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("admin.ExtractPipelineRequest").msgclass
  RestoreRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("admin.RestoreRequest").msgclass
  ClusterInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("admin.ClusterInfo").msgclass
end
