# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: client/admin/admin.proto for package 'admin'

require 'grpc'
require 'client/admin/admin_pb'

module Admin
  module API
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'admin.API'

      rpc :Extract, ExtractRequest, stream(Op)
      rpc :ExtractPipeline, ExtractPipelineRequest, Op
      rpc :Restore, stream(RestoreRequest), Google::Protobuf::Empty
      rpc :InspectCluster, Google::Protobuf::Empty, ClusterInfo
    end

    Stub = Service.rpc_stub_class
  end
end
