# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/pkg/shard/shard.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "shard.ServerState" do
    optional :address, :string, 1
    optional :version, :int64, 2
  end
  add_message "shard.FrontendState" do
    optional :address, :string, 1
    optional :version, :int64, 2
  end
  add_message "shard.ServerRole" do
    optional :address, :string, 1
    optional :version, :int64, 2
    map :shards, :uint64, :bool, 3
  end
  add_message "shard.Addresses" do
    optional :version, :int64, 1
    map :addresses, :uint64, :string, 2
  end
  add_message "shard.StartRegister" do
    optional :address, :string, 1
  end
  add_message "shard.FinishRegister" do
    optional :address, :string, 1
    optional :error, :string, 2
  end
  add_message "shard.Version" do
    optional :result, :int64, 1
    optional :error, :string, 2
  end
  add_message "shard.StartAssignRoles" do
  end
  add_message "shard.FinishAssignRoles" do
    optional :error, :string, 1
  end
  add_message "shard.FailedToAssignRoles" do
    map :server_states, :string, :message, 1, "shard.ServerState"
    optional :num_shards, :uint64, 2
    optional :num_replicas, :uint64, 3
  end
  add_message "shard.SetServerState" do
    optional :serverState, :message, 1, "shard.ServerState"
  end
  add_message "shard.SetFrontendState" do
    optional :frontendState, :message, 1, "shard.FrontendState"
  end
  add_message "shard.AddServerRole" do
    optional :serverRole, :message, 1, "shard.ServerRole"
    optional :error, :string, 2
  end
  add_message "shard.RemoveServerRole" do
    optional :serverRole, :message, 1, "shard.ServerRole"
    optional :error, :string, 2
  end
  add_message "shard.SetServerRole" do
    optional :serverRole, :message, 2, "shard.ServerRole"
  end
  add_message "shard.DeleteServerRole" do
    optional :serverRole, :message, 2, "shard.ServerRole"
  end
  add_message "shard.SetAddresses" do
    optional :addresses, :message, 1, "shard.Addresses"
  end
  add_message "shard.GetAddress" do
    optional :shard, :uint64, 1
    optional :version, :int64, 2
    optional :result, :string, 3
    optional :ok, :bool, 4
    optional :error, :string, 5
  end
  add_message "shard.GetShardToAddress" do
    optional :version, :int64, 1
    map :result, :uint64, :string, 2
    optional :error, :string, 3
  end
end

module Shard
  ServerState = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.ServerState").msgclass
  FrontendState = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.FrontendState").msgclass
  ServerRole = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.ServerRole").msgclass
  Addresses = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.Addresses").msgclass
  StartRegister = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.StartRegister").msgclass
  FinishRegister = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.FinishRegister").msgclass
  Version = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.Version").msgclass
  StartAssignRoles = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.StartAssignRoles").msgclass
  FinishAssignRoles = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.FinishAssignRoles").msgclass
  FailedToAssignRoles = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.FailedToAssignRoles").msgclass
  SetServerState = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.SetServerState").msgclass
  SetFrontendState = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.SetFrontendState").msgclass
  AddServerRole = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.AddServerRole").msgclass
  RemoveServerRole = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.RemoveServerRole").msgclass
  SetServerRole = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.SetServerRole").msgclass
  DeleteServerRole = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.DeleteServerRole").msgclass
  SetAddresses = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.SetAddresses").msgclass
  GetAddress = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.GetAddress").msgclass
  GetShardToAddress = Google::Protobuf::DescriptorPool.generated_pool.lookup("shard.GetShardToAddress").msgclass
end
