# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: client/deploy/deploy.proto for package 'deploy'

require 'grpc'
require 'client/deploy/deploy_pb'

module Pachyderm
module Deploy
  module API
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'deploy.API'

      rpc :DeployStorageSecret, DeployStorageSecretRequest, DeployStorageSecretResponse
    end

    Stub = Service.rpc_stub_class
  end
end
end
