#!/bin/bash

tar xf /dev/stdin

#directory where we want these declarations to live in the 'ruby_pachyderm' repo
outdir=lib/
mkdir -p $outdir

for i in $(find ./proto/pachyderm/src/client -maxdepth 7 -name "*.proto"); do \
    # make sure to remove the gogoproto line, as that is go specific
    sed -i s/import.*gogo.proto.*\;// $i
    sed -i 's/\[.*gogoproto.*\]//' $i
    # we need to do this in a pass before compilation because it's not guaranteed we
    # traverse the proto files in order of dependence
done

for i in $(find ./proto/pachyderm/src/client -maxdepth 7 -name "*.proto"); do \
    grpc_tools_ruby_protoc -I ./proto/pachyderm/src --ruby_out=$outdir --grpc_out=$outdir ${i}; \
done

# Fix module namespace in emitted ruby files
for i in $(find $OUTDIR -maxdepth 7 -regex ".*pb.rb"); do
	# Put additional 'Pachyderm' module declaration before top level modules
    sed -iE 's/^module \(.*\)$/module Pachyderm\nmodule \1/g' $i
	# Add additional 'end' to complete the wrap, but only if the file ends w an 'end'. Hacky.
	if [[ $(cat $i | tail -n 1 | grep end) ]]; then
		echo 'end' >> $i
	fi
done

find $outdir -maxdepth 5 -regex ".*pb.rb" | xargs tar cf -

