# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: client/pps/pps.proto for package 'pps'

require 'grpc'
require 'client/pps/pps_pb'

module Pachyderm
module Pps
  module API
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pps.API'

      rpc :CreateJob, CreateJobRequest, Job
      rpc :InspectJob, InspectJobRequest, JobInfo
      # ListJob returns information about current and past Pachyderm jobs. This is
      # deprecated in favor of ListJobStream
      rpc :ListJob, ListJobRequest, JobInfos
      # ListJobStream returns information about current and past Pachyderm jobs.
      rpc :ListJobStream, ListJobRequest, stream(JobInfo)
      rpc :FlushJob, FlushJobRequest, stream(JobInfo)
      rpc :DeleteJob, DeleteJobRequest, Google::Protobuf::Empty
      rpc :StopJob, StopJobRequest, Google::Protobuf::Empty
      rpc :InspectDatum, InspectDatumRequest, DatumInfo
      # ListDatum returns information about each datum fed to a Pachyderm job. This
      # is deprecated in favor of ListDatumStream
      rpc :ListDatum, ListDatumRequest, ListDatumResponse
      # ListDatumStream returns information about each datum fed to a Pachyderm job
      rpc :ListDatumStream, ListDatumRequest, stream(ListDatumStreamResponse)
      rpc :RestartDatum, RestartDatumRequest, Google::Protobuf::Empty
      rpc :CreatePipeline, CreatePipelineRequest, Google::Protobuf::Empty
      rpc :InspectPipeline, InspectPipelineRequest, PipelineInfo
      rpc :ListPipeline, ListPipelineRequest, PipelineInfos
      rpc :DeletePipeline, DeletePipelineRequest, Google::Protobuf::Empty
      rpc :StartPipeline, StartPipelineRequest, Google::Protobuf::Empty
      rpc :StopPipeline, StopPipelineRequest, Google::Protobuf::Empty
      rpc :RerunPipeline, RerunPipelineRequest, Google::Protobuf::Empty
      # DeleteAll deletes everything
      rpc :DeleteAll, Google::Protobuf::Empty, Google::Protobuf::Empty
      rpc :GetLogs, GetLogsRequest, stream(LogMessage)
      # Garbage collection
      rpc :GarbageCollect, GarbageCollectRequest, GarbageCollectResponse
      # An internal call that causes PPS to put itself into an auth-enabled state
      # (all pipeline have tokens, correct permissions, etcd)
      rpc :ActivateAuth, ActivateAuthRequest, ActivateAuthResponse
    end

    Stub = Service.rpc_stub_class
  end
end
end
