# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: client/version/versionpb/version.proto for package 'versionpb'

require 'grpc'
require 'client/version/versionpb/version_pb'

module Versionpb
  module API
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'versionpb.API'

      rpc :GetVersion, Google::Protobuf::Empty, Version
    end

    Stub = Service.rpc_stub_class
  end
end
