# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/version/versionpb/version.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "versionpb.Version" do
    optional :major, :uint32, 1
    optional :minor, :uint32, 2
    optional :micro, :uint32, 3
    optional :additional, :string, 4
  end
end

module Pachyderm
module Versionpb
  Version = Google::Protobuf::DescriptorPool.generated_pool.lookup("versionpb.Version").msgclass
end
end
