# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/health/health.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Health
end
